import 'the-new-css-reset';
import '@/styles/globals.css';
import type { Metadata } from 'next';
import { IBM_Plex_Sans_JP } from 'next/font/google';

const ibmPlexSansJp = IBM_Plex_Sans_JP({
  weight: ['400'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Next.js + OpenCV Hooks',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${ibmPlexSansJp.className}`}>{children}</body>
    </html>
  );
}
